[package]
name = "rshtml_test"
version = "0.1.0"
edition = "2024"

build = "build.rs"

[dependencies]
rshtml = { path = "../rshtml" }
rshtml_macro = { path = "../rshtml_macro" }
chrono = "0.4.41"

[package.metadata.rshtml]
views_base_path = "src/views"
layout = "layout.rs.html"