[package]
name = "rshtml_test"
version = "0.1.0"
edition = "2024"

[dependencies]
rshtml = { path = "../rshtml" }
chrono = "0.4.41"
syn = "2.0.101"
pest = "2.8.0"
serde = { version = "1.0.219", features = ["derive"] }
axum = "0.8.4"
tokio = { version = "1.45.1", features = ["full"] }
tracing-subscriber = "0.3.19"
tracing = "0.1.41"

[package.metadata.rshtml]
views = { path = "views", layout = "layout.rs.html" }

[build-dependencies]
rshtml = { path = "../rshtml" }
