[package]
name = "rshtml"
version = "0.1.0"
edition = "2024"

[dependencies]
pest = "2.8.0"
pest_derive = "2.8.0"
serde = { version = "1.0.219", features = ["derive"] }
quote = "1.0.40"
proc-macro2 = "1.0.95"
eyre = "0.6.12"
toml = "0.8.22"
syn = { version = "2.0.101", features = ["full"] }