[package]
name = "rshtml"
documentation = "https://docs.rs/rshtml"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
rshtml_macro.workspace = true
rshtml_core.workspace = true