[package]
name = "rshtml"
version = "0.1.0"
edition = "2024"

[dependencies]
pest = "2.8.0"
pest_derive = "2.8.0"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
quote = "1.0.40"
proc-macro2 = "1.0.95"