[package]
name = "rshtml_macro"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.27", features = ["full"] }
rshtml_core.workspace = true